version: '2.4'

services:
  postgres:
    container_name: students_postgres
    environment:
      POSTGRES_HOST_AUTH_METHOD: scram-sha-256
      POSTGRES_INITDB_ARGS: --auth-host=scram-sha-256
      POSTGRES_DB: students
      POSTGRES_USER: students
      POSTGRES_PASSWORD: students
    image: postgres:14-alpine3.15
    ports:
      - "5432:5432"
    volumes:
      - type: volume
        source: postgres_data
        target: /var/lib/postgresql/data

volumes:
  postgres_data: